name: CI
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies (LLVM 18)
      run: sudo apt update && sudo apt install llvm-18-dev libpolly-18-dev
    - name: Install dependencies (QBE)
      run: git clone git://c9x.me/qbe.git && cd qbe && make && sudo make install
    - name: Install dependencies (Rust nightly)
      run: rustup default nightly
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test
  format:
    name: Format
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies (Rust nightly)
      run: rustup default nightly && rustup component add rustfmt
    - name: Verify formatter
      run: cargo fmt -- --check
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies (Rust nightly)
      run: rustup default nightly && rustup component add clippy
    - name: Verify linter
      run: cargo clippy -- -D warnings
